import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { chromium } from 'playwright';
import { createApplication } from '../server.mjs';

test('browser: owner setup, invite acceptance, role access, shared notes, and mobile layout', { skip: !process.env.CHROME_PATH }, async () => {
  const dataDir = await mkdtemp(path.join(tmpdir(), 'pulse-browser-'));
  const app = await createApplication({ dataDir, databaseUrl: '' });
  await new Promise(resolve => app.server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${app.server.address().port}`;
  let browser;
  try {
    browser = await chromium.launch({ executablePath: process.env.CHROME_PATH, headless: true });
    const ownerContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const owner = await ownerContext.newPage();
    const errors = [];
    owner.on('pageerror', error => errors.push(error.message));
    await owner.goto(base);
    await owner.locator('#signin-name').fill('Workspace Owner');
    await owner.locator('#signin-email').fill('owner@example.com');
    await owner.locator('#signin-password').fill('browser-test-password');
    await owner.locator('#confirm-password').fill('browser-test-password');
    await owner.getByRole('button', { name: 'Create account & sign in' }).click();
    await owner.locator('.workspace').waitFor();
    await owner.getByRole('button', { name: 'Team', exact: true }).click();
    await owner.locator('#invite-profile').selectOption('jamie');
    await owner.locator('#invite-name').fill('Jamie <img src=x onerror=alert(1)>');
    await owner.locator('#invite-email').fill('jamie@example.com');
    await owner.getByRole('button', { name: 'Create invitation' }).click();
    await owner.locator('#invite-link').waitFor();
    const link = await owner.locator('#invite-link').inputValue();
    assert.ok(link.startsWith(base + '/#invite='));
    await mkdir('test-results', { recursive: true });
    // Hide the single-use URL from the saved screenshot.
    await owner.screenshot({ path: 'test-results/team-desktop.png', fullPage: true, mask: [owner.locator('#invite-link')] });
    const techContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
    const tech = await techContext.newPage();
    tech.on('pageerror', error => errors.push(error.message));
    await tech.goto(link);
    await tech.getByRole('heading', { name: 'Accept your invitation.' }).waitFor();
    assert.equal(await tech.locator('.login-form img').count(), 0);
    await tech.locator('#signin-password').fill('technician-test-password');
    await tech.locator('#confirm-password').fill('technician-test-password');
    await tech.getByRole('button', { name: 'Join workspace' }).click();
    await tech.locator('.workspace').waitFor();
    assert.equal(await tech.getByRole('button', { name: 'Team', exact: true }).count(), 0);
    assert.equal(await tech.locator('.page-heading img').count(), 0);
    await tech.getByRole('button', { name: 'Nest thermostat installation', exact: true }).click();
    assert.equal(await tech.locator('#schedule-form').count(), 0);
    await tech.locator('#note-text').fill('Shared browser note');
    await tech.getByRole('button', { name: 'Add note' }).click();
    await tech.getByText('Shared browser note', { exact: true }).waitFor();
    await tech.getByRole('button', { name: 'Close job details' }).click();
    assert.ok(await tech.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await tech.screenshot({ path: 'test-results/technician-mobile.png', fullPage: true });
    await owner.reload();
    await owner.getByRole('button', { name: 'Nest thermostat installation', exact: true }).click();
    await owner.getByText('Shared browser note', { exact: true }).waitFor();
    await owner.getByRole('button', { name: 'Close job details' }).click();
    await owner.setViewportSize({ width: 390, height: 844 });
    await owner.getByRole('button', { name: 'Team', exact: true }).click();
    assert.ok(await owner.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await owner.screenshot({ path: 'test-results/team-mobile.png', fullPage: true });
    await tech.getByRole('button', { name: 'Sign out', exact: true }).click();
    await tech.getByRole('heading', { name: 'Welcome back.' }).waitFor();
    await tech.locator('#signin-email').fill('jamie@example.com');
    await tech.locator('#signin-password').fill('wrong');
    await tech.getByRole('button', { name: 'Sign in', exact: true }).click();
    await tech.getByText('Email or password is incorrect.').waitFor();
    assert.deepEqual(errors, []);
  } finally { if (browser) await browser.close(); await app.close(); }
});
